# Project metadata
sonar.projectKey=go-generics
sonar.projectName=go-generics

# Source
sonar.sources=.
sonar.inclusions=**/*.go
sonar.exclusions=**/*_test.go,vendor/**,**/test/**
sonar.sourceEncoding=UTF-8

# Tests
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.test.exclusions=**/vendor/**

# Coverage
sonar.go.coverage.reportPaths=cover.out
sonar.go.golangci-lint.reportPaths=lint-report.out
