name: Release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

# Default permissions for all jobs - deny all by default
permissions: {}

jobs:
  release:
    runs-on: [ubuntu-24.04]
    # Needs to read repository contents, create tags and releases
    permissions:
      contents: write  # Required for creating releases and tags
    if:
      ${{
        (github.event.pull_request.merged == true && (
          contains(github.event.pull_request.labels.*.name, 'create-patch-release') ||
          contains(github.event.pull_request.labels.*.name, 'create-minor-release') ||
          contains(github.event.pull_request.labels.*.name, 'create-major-release')
        )) || github.event_name == 'workflow_dispatch'
      }}

    # This may only be run by repository admins.
    environment: admin-approval
    outputs:
      version_type: ${{ steps.type.outputs.version_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version type
        id: type
        run: |
          set -ex -o pipefail
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            echo "::set-output name=version_type::${{ github.event.inputs.release_type }}"
          elif [ ${{ contains(github.event.pull_request.labels.*.name, 'create-major-release') }} ]; then
            echo "::set-output name=version_type::major"
          elif [ ${{ contains(github.event.pull_request.labels.*.name, 'create-minor-release') }} ]; then
            echo "::set-output name=version_type::minor"
          else
            echo "::set-output name=version_type::patch"
          fi

      - name: Compute tag
        uses: craig-day/compute-tag@v13
        id: tag
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: ${{ steps.type.outputs.version_type }}

      - name: Create release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ steps.tag.outputs.next_tag }}
          release_name: ${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/${{ steps.tag.outputs.previous_tag }}...${{ steps.tag.outputs.next_tag }}) for release details.
