name: release

on:
  pull_request:
    types:
      - closed
    branches:
      - main
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: [ubuntu-24.04]
    if:
      ${{
        (github.event.pull_request.merged == true && (
          contains(github.event.pull_request.labels.*.name, 'create-patch-release') ||
          contains(github.event.pull_request.labels.*.name, 'create-minor-release') ||
          contains(github.event.pull_request.labels.*.name, 'create-major-release')
        )) || github.event_name == 'workflow_dispatch'
      }}

    # This may only be run by repository admins.
    environment: admin-approval
    outputs:
      version_type: ${{ steps.type.outputs.version_type }}
    steps:
      - uses: actions/checkout@v3
      - name: Set version type
        id: type
        run: |
          set -ex -o pipefail
          if [ ${{ github.event_name }} == 'workflow_dispatch' ]; then
            echo "::set-output name=version_type::${{ github.event.inputs.release_type }}"
          elif [ ${{ contains(github.event.pull_request.labels.*.name, 'create-major-release') }} ]; then
            echo "::set-output name=version_type::major"
          elif [ ${{ contains(github.event.pull_request.labels.*.name, 'create-minor-release') }} ]; then
            echo "::set-output name=version_type::minor"
          else
            echo "::set-output name=version_type::patch"
          fi

      - name: Compute tag
        uses: craig-day/compute-tag@v13
        id: tag
        with:
          github_token: ${{ github.token }}
          version_scheme: semantic
          version_type: ${{ steps.type.outputs.version_type }}

      - name: Run publish
        id: publish
        env:
          ARTIFACT_VERSION: v${{ steps.tag.outputs.next_tag }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./scripts/publish.sh
          git config user.name "Version Release"
          git config user.email "github@ga-runner.zende.sk"
          git add -A
          git commit -m "Release version ${{ steps.tag.outputs.next_tag }}"
          git push
          hash=$(git rev-parse HEAD)
          echo "commit_hash=$hash" >> $GITHUB_OUTPUT
          echo "Setting commit_hash to: $hash in GH output."

      - name: Create release base
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: v${{ steps.tag.outputs.next_tag }}
          release_name: v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release test
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: test/v${{ steps.tag.outputs.next_tag }}
          release_name: test/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release serialize
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: serialize/v${{ steps.tag.outputs.next_tag }}
          release_name: serialize/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.
      - name: Create release concurrency
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: concurrency/v${{ steps.tag.outputs.next_tag }}
          release_name: concurrency/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.
      - name: Create release datastructures
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: datastructures/v${{ steps.tag.outputs.next_tag }}
          release_name: datastructures/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release ratelimit
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ratelimit/v${{ steps.tag.outputs.next_tag }}
          release_name: ratelimit/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release encryption
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: encryption/v${{ steps.tag.outputs.next_tag }}
          release_name: encryption/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release cache
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: cache/v${{ steps.tag.outputs.next_tag }}
          release_name: cache/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

      - name: Create release functions
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: functions/v${{ steps.tag.outputs.next_tag }}
          release_name: functions/v${{ steps.tag.outputs.next_tag }}
          commitish: ${{ steps.publish.outputs.commit_hash }}
          body: |
            See [changes since last release](https://github.com/${{ github.repository }}/compare/v${{ steps.tag.outputs.previous_tag }}...v${{ steps.tag.outputs.next_tag }}) for release details.

